language: objective-c
osx_image: xcode8.2

script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -sdk iphonesimulator10.2 -project tmdb.xcodeproj -scheme tmdb -destination 'platform=iOS Simulator,id=3B5E817B-744D-4086-AAB0-55CB35A17717,OS=10.1,name=iPhone 6' -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
