language: objective-c
osx_image: xcode8.2

script:
        - set -o pipefail
        - xcodebuild -version
        - xcodebuild -showsdks
        - xcodebuild test -sdk iphonesimulator10.2 -project tmdb.xcodeproj -scheme tmdb -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 5' -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO
